# Generated by Django 5.0.7 on 2024-07-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SotsCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('candidate_id', models.CharField(max_length=50, unique=True)),
                ('roles', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('terminated', 'Terminated')], max_length=10, null=True)),
                ('display_summary', models.TextField(max_length=250)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('current_location', models.CharField(max_length=100)),
                ('work_mode', models.CharField(max_length=50)),
                ('work_type', models.CharField(max_length=50)),
                ('hard_skills', models.TextField()),
                ('soft_skills', models.TextField()),
                ('tools', models.TextField()),
                ('tag', models.TextField()),
                ('experience_summary', models.TextField()),
                ('educational_summary', models.TextField()),
                ('certifications', models.TextField()),
                ('additional_note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
